In [13]:
import torch
a = (torch.tensor([1, 3,4]))
b = torch.tensor([2,5,6])
type(a)
torch.stack((a,b)).shape

torch.Size([2, 3])

In [18]:
torch.stack([a,b])

tensor([[1, 3, 4],
        [2, 5, 6]])

In [17]:
from train import train_set
num_iters = 100
idx = torch.randint(0, len(train_set), (10,3)) # num_iters, 
print(idx)

tensor([[ 564988, 2343102,  976333],
        [2546504, 2409234,  579754],
        [ 809687, 3196377, 2429979],
        [3266867, 1948477,  517394],
        [2406457, 1079921,  165078],
        [ 328943,  762094,  350631],
        [3088030, 1074577, 1016121],
        [1908999, 3191367, 2908703],
        [ 465343, 3445781, 2924816],
        [1601079, 3169589, 3167899]])


In [ ]:
# idx (num_iters, B)
from train import config
print(config) # Config(vocab_size=101, batch_size=32, context_len=8, embd_dim=8, num_heads=4, bias=False)
context_len = torch.tensor(config.context_len)
# [[[idx[i,b]] for i in range(10)] for b in range(3)]
train_batch_list = [[train_set[idx[i,b]: idx[i,b] + config.context_len + 1] for b in range(3)] for i in range(10)]
# [[train_set[s: s+context_len + 1] for s in idx[:torch.tensor(b)]] for b in range(config.batch_size)]
train_batch_tensor = torch.tensor(train_batch_list)
print(train_batch_tensor.shape)
print(train_batch_tensor.squeeze(2).shape)
print(train_batch_tensor.shape)
# btw I didn't have to complicate it this early! I could've just used the whole dataset instead of incorporating num_iters into this randomizer index.

# but looks like i didn't need the stack? 

Config(vocab_size=101, batch_size=32, context_len=8, embd_dim=8, num_heads=4, bias=False)
torch.Size([10, 3, 9])
torch.Size([10, 3, 9])
torch.Size([10, 3, 9])


In [63]:
import numpy as np
print(torch.range(0, 9))
print(torch.arange(0, 9))
print(np.arange(0,9))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
[0 1 2 3 4 5 6 7 8]


/var/folders/v9/_vy4y7rj0pnb0chq9mb1wb440000gn/T/ipykernel_41153/1791158308.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(0, 9))


In [67]:
torch.randint(0,3, (10,))

tensor([0, 2, 2, 1, 2, 1, 2, 1, 0, 0])

In [69]:
train_batch_tensor.shape

torch.Size([10, 3, 9])